feature/1: Initial Implementation
exasol/google-cloud-storage-document-files-virtual-schema pull request #2
Opened 2022-01-31 14:16 UTC by jakobbraun

Closes #1

2022-02-01 09:53 UTC, morazow requested changes

2022-02-01 09:53 UTC, morazow commented on src/main/java/com/exasol/adapter/document/files/GcsDocumentFilesAdapterFactory.java
> + * Factory for the S3 virtual schema adapter.
```suggestion
 * Factory for the GCS Virtual Schema adapter.
```

2022-02-01 09:53 UTC, morazow commented on src/main/java/com/exasol/adapter/document/files/GcsObjectDescription.java
> + * This class represents a reference to a S3 object.
```suggestion
 * This class represents a reference to a GCS object.
```

2022-02-01 09:53 UTC, morazow commented on src/main/java/com/exasol/adapter/document/files/GcsRemoteFileContent.java
> +    /** Exception message used by S3 if there were too many API requests. */
```suggestion
```

2022-02-01 09:53 UTC, morazow commented on src/main/java/com/exasol/adapter/document/files/connection/GcsConnectionProperties.java
> +        return this.gcHost != null && !this.gcHost.isBlank() && !this.gcHost.equals("amazonaws.com");
Does GCS has default storage host? If so, please update `amazonaws.com` with it.

2022-02-01 10:06 UTC, jakobbraun commented on doc/user_guide/user_guide.md
> +        "gcKey":  {
The idea behind gcKey is that it's generic for different services on the google-cloud. The key is not specific for the storage service.

2022-02-01 10:06 UTC, jakobbraun commented on doc/user_guide/user_guide.md
> +\* The adapter will start at most one UDF per input file. That means, if data from a single file (for example a JSON-Lines file) is loaded, it will not parallelize.
no, it's outdated.

2022-02-01 10:06 UTC, jakobbraun commented on doc/user_guide/user_guide.md
> +\* The adapter will start at most one UDF per input file. That means, if data from a single file (for example a JSON-Lines file) is loaded, it will not parallelize.
```suggestion
```

2022-02-01 11:03 UTC, morazow requested changes

2022-02-01 15:06 UTC, jakobbraun commented on doc/developers_guide/developers_guide.md
> +This guide contains information for developers.
I need to update this file.

2022-02-01 16:01 UTC, morazow submitted a review, later dismissed
Minor typo, then looks good

2022-02-02 07:25 UTC, redcatbear approved these changes

2022-02-02 07:27 UTC, merged